# Generated by Django 4.0.5 on 2022-07-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_alter_produto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_markenting',
            field=models.FloatField(verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_markenting_promocional',
            field=models.FloatField(default=0, verbose_name='Preço Promo'),
        ),
    ]
