# Generated by Django 4.0.5 on 2022-07-03 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_pedido_qtd_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='produt_id',
            new_name='produto_id',
        ),
    ]
